### PR TITLE
Add attachment support.

### PR DESCRIPTION
**Pull request by Jimbo1167**

### CODE REVIEW

**Comment by Jimbo1167** [comment]
Hey dpacaud,

It's me again, I have another outstanding pull request out for the mandrill
plugin, just wondering if there's anything I can do to get that merged up.

Thanks,

James Schindler

**Comment by dpacaud** [comment]
Hey James,

sorry for the delay, I had an accident which impacted my ability to merge your request :(

It has been merged now and the plugin has been published with your latest modifications.

Regards,
-- 
Damien

Le 25 mars 2014 à 19:42:02, James Schindler (notifications@github.com) a écrit:

Hey dpacaud,

It's me again, I have another outstanding pull request out for the mandrill
plugin, just wondering if there's anything I can do to get that merged up.

Thanks,

James Schindler

**Comment by cjf** [comment]
So how does one add an attachment?  What is the proper format for a MandrillAttachment if I'm trying to create/add csv content?  Just putting in normal string data doesn't seem to work.  The attachment ends up being delivered as binary jibberish.

**Comment by Jimbo1167** [comment]
@cjf The content of the attachment as a base64-encoded string.

For more info you can take a look at the API docs here:
https://mandrillapp.com/api/docs/messages.JSON.html

**Pull request merged**
